[build]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=--gc-sections",
    "-C", "force-frame-pointers=no",
    "-C", "code-model=medium",
]

[alias]
kbuild = "build --release -p onyx_kernel --target riscv64gc-unknown-none-elf"
ibuild = "build --release -p onyx_init --target riscv64gc-unknown-none-elf"
tbuild = "build --release -p onyx_tools"
